### PR TITLE
Fix logic around adding bcrypt gem based on current state

### LINKED ISSUE #41: bcrypt is always added to the Gemfile when it should be uncommented
If the `Gemfile` contains `bcrypt` (but commented out) the script should be un-commenting this line. Right now, we have logic in place to do this, but it's not working.

### PR DESCRIPTION
**Pull request by eclectic-coding**
Steve,
This should fix #41 

The generator will now uncomment the `bcrypt` line in the `Gemfile`, or in the cases where the line is already uncommented, it will not add a new reference to the gem.

### CODE REVIEW

**Review by stevepolitodesign — COMMENTED** [review]
Thank you for looking into this! After giving it some thought, I think the root cause of this issue is my equality check.

```ruby
return true if line == '# gem "bcrypt", "~> 3.1.7"'
```

I think the reason this branch is not getting hit is that there's probably a `\n` character on that line. Additionally, this is making me realize that the Gem version should **not** be part of the equality check. Instead, we just want to check for the Gem name.

```ruby
line.strip.start_with?("#") && line.include?("bycrypt")
```

It looks like some extra files might have been added, so we'll want to remove those.

**Comment by eclectic-coding** [comment]
Thanks Steve, I will work on today.

I agree, and I like your approach. I was thinking that the version number would make this generator harder to maintain. So, without the version number it is more generic and will not break if there is a point release change in the default Rails Gemfile.

**Comment by eclectic-coding** [comment]
Finished the changes @stevepolitodesign 

I created a sample test app, and tested all three conditions and it seems to work now:
- gem commented out
- gem not commented out
- gem not listed at all in the gemfile

**Review by stevepolitodesign — APPROVED** [review]
This is great! The only thing I need to now consider (in a separate commit), is improving this script to account for the version dynamically.

Right now, Rails [sets](https://github.com/rails/rails/blob/c9780350f27efd6332ec9593123f80d02eeb198b/activemodel/lib/active_model/secure_password.rb#L42) the [pessimistic operator](https://thoughtbot.com/blog/rubys-pessimistic-operator) to `3.1.7`, but that could change.

Rails will most likely have the [Gem commented out](https://github.com/rails/rails/blob/c9780350f27efd6332ec9593123f80d02eeb198b/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L15), so we can always parse the Gemfile for that `bcrypt`, and get the version there.

**Pull request merged**
